[debian] make sure Xorg initscript waits for Xorg to be ready to launch clients
Ignore-this: 2d20def3e2d838280f324cedb68127b5

darcs-hash:20090826200246-85ee7-de45599bc8715e7f62415eeef7cdec66defec64c.gz

committer: Alexandre Rossi <alexandre.rossi@gmail.com>

diff --git a/debian/deejayd.deejayd-xserver.init b/debian/deejayd.deejayd-xserver.init
--- a/debian/deejayd.deejayd-xserver.init
+++ b/debian/deejayd.deejayd-xserver.init
@@ -119,6 +119,15 @@ do_start()
         --exec $DAEMON\
         -b -c $DAEMON_USER -- $DAEMON_ARGS \
         || return 2
+
+    # Wait for the X server to accept X connections.
+    maxtries=40
+    tries=0
+    while [ "`xorg_ping`" != "pong" ] && [ $tries -lt $maxtries ]
+    do
+        tries=`expr $tries + 1`
+        sleep 0.5
+    done
 }
 
 do_start_xclients()
@@ -180,6 +189,15 @@ is_alive () {
         fi
     fi
     return $ret
+}
+
+xorg_ping () {
+    # This function checks if a basic X client can probe the X server.
+    /usr/bin/xprop -root -display $authdisplay > /dev/null 2> /dev/null
+    case "$?" in
+        0) echo "pong" && return 0;;
+        *) echo "fail" && return 1;;
+    esac
 }
 
 case "$1" in
